In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston # 보스턴 주택값 데이터

In [2]:
boston = load_boston()

C:\Users\smhrd\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [4]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [5]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
boston.data # 부동소수

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
# 데이터 프레임
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)

In [10]:
boston_df #문제

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [11]:
house_price =boston.target #정답

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(boston_df,house_price,test_size=0.3)

In [15]:
boston_copy=X_train.copy() #복사본 만들기

In [17]:
boston_copy['PRICE'] = y_train # 정답컬럼 만들어주기 (상관관계 체크를 위해)

In [19]:
boston_copy.corr()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
CRIM     1.000000 -0.202357  0.380712 -0.053197  0.388820 -0.189949  0.342170   
ZN      -0.202357  1.000000 -0.569834 -0.039634 -0.550166  0.297802 -0.620182   
INDUS    0.380712 -0.569834  1.000000  0.061320  0.771438 -0.372961  0.693855   
CHAS    -0.053197 -0.039634  0.061320  1.000000  0.109236  0.129455  0.092799   
NOX      0.388820 -0.550166  0.771438  0.109236  1.000000 -0.306217  0.742395   
RM      -0.189949  0.297802 -0.372961  0.129455 -0.306217  1.000000 -0.254267   
AGE      0.342170 -0.620182  0.693855  0.092799  0.742395 -0.254267  1.000000   
DIS     -0.365725  0.691220 -0.739734 -0.108185 -0.777194  0.186954 -0.764762   
RAD      0.595845 -0.331849  0.578407  0.007744  0.587326 -0.194620  0.465252   
TAX      0.555072 -0.350364  0.720372 -0.024223  0.658638 -0.284569  0.533398   
PTRATIO  0.268467 -0.394308  0.376111 -0.125753  0.182717 -0.329979  0.266471   
B       -0.374261  0.189438 -0.348766  0.050460 -0.357246  0.132087 -0.270254   
LSTAT    0.391464 -0.431411  0.598638 -0.043147  0.580883 -0.618128  0.603864   
PRICE   -0.363926  0.348694 -0.446849  0.192737 -0.416800  0.677957 -0.375330   

              DIS       RAD       TAX   PTRATIO         B     LSTAT     PRICE  
CRIM    -0.365725  0.595845  0.555072  0.268467 -0.374261  0.391464 -0.363926  
ZN       0.691220 -0.331849 -0.350364 -0.394308  0.189438 -0.431411  0.348694  
INDUS   -0.739734  0.578407  0.720372  0.376111 -0.348766  0.598638 -0.446849  
CHAS    -0.108185  0.007744 -0.024223 -0.125753  0.050460 -0.043147  0.192737  
NOX     -0.777194  0.587326  0.658638  0.182717 -0.357246  0.580883 -0.416800  
RM       0.186954 -0.194620 -0.284569 -0.329979  0.132087 -0.618128  0.677957  
AGE     -0.764762  0.465252  0.533398  0.266471 -0.270254  0.603864 -0.375330  
DIS      1.000000 -0.502891 -0.549305 -0.237618  0.293932 -0.490501  0.230878  
RAD     -0.502891  1.000000  0.906677  0.451080 -0.418089  0.422344 -0.347210  
TAX     -0.549305  0.906677  1.000000  0.453814 -0.423473  0.491328 -0.442660  
PTRATIO -0.237618  0.451080  0.453814  1.000000 -0.158491  0.314692 -0.469580  
B        0.293932 -0.418089 -0.423473 -0.158491  1.000000 -0.318064  0.320048  
LSTAT   -0.490501  0.422344  0.491328  0.314692 -0.318064  1.000000 -0.723917  
PRICE    0.230878 -0.347210 -0.442660 -0.469580  0.320048 -0.723917  1.000000

### LinearRegression

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [21]:
#모델 생성
linear_model = LinearRegression()

In [23]:
#모델 학습
linear_model.fit(boston_copy.loc[:,:'LSTAT'],boston_copy['PRICE']) # x트레인/y트레인

LinearRegression()

In [24]:
#교차 검증
linear_result=cross_val_score(linear_model,X_train,y_train,cv=5)
linear_result

array([0.82025204, 0.67111155, 0.63937884, 0.66632043, 0.6347532 ])

In [25]:
linear_result.mean()

0.6863632116810182

In [26]:
X_train

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
105   0.13262   0.0   8.56   0.0  0.520  5.851   96.7  2.1069   5.0  384.0   
129   0.88125   0.0  21.89   0.0  0.624  5.637   94.7  1.9799   4.0  437.0   
399   9.91655   0.0  18.10   0.0  0.693  5.852   77.8  1.5004  24.0  666.0   
13    0.62976   0.0   8.14   0.0  0.538  5.949   61.8  4.7075   4.0  307.0   
292   0.03615  80.0   4.95   0.0  0.411  6.630   23.4  5.1167   4.0  245.0   
..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
161   1.46336   0.0  19.58   0.0  0.605  7.489   90.8  1.9709   5.0  403.0   
504   0.10959   0.0  11.93   0.0  0.573  6.794   89.3  2.3889   1.0  273.0   
311   0.79041   0.0   9.90   0.0  0.544  6.122   52.8  2.6403   4.0  304.0   
386  24.39380   0.0  18.10   0.0  0.700  4.652  100.0  1.4672  24.0  666.0   
415  18.08460   0.0  18.10   0.0  0.679  6.434  100.0  1.8347  24.0  666.0   

     PTRATIO       B  LSTAT  
105     20.9  394.05  16.47  
129     21.2  396.90  18.34  
399     20.2  338.16  29.97  
13      21.0  396.90   8.26  
292     19.2  396.90   4.70  
..       ...     ...    ...  
161     14.7  374.43   1.73  
504     21.0  393.45   6.48  
311     18.4  396.90   5.98  
386     20.2  396.90  28.28  
415     20.2   27.25  29.05  

[354 rows x 13 columns]

### 특성 확장

In [28]:
extended_X_train = X_train.copy()

In [31]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [32]:
b = a
b

[1, 2, 3, 4]

In [33]:
a.append(320)

In [34]:
a

[1, 2, 3, 4, 320]

In [35]:
b

[1, 2, 3, 4, 320]

In [36]:
c = a.copy()
c

[1, 2, 3, 4, 320]

In [37]:
a.append(100000)

In [38]:
c

[1, 2, 3, 4, 320]

In [39]:
a

[1, 2, 3, 4, 320, 100000]

In [40]:
for col1 in X_train.columns:
    for col2 in X_train.columns:
        extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]

C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, wh

C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, wh

C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_train[col1+'x'+col2] = X_train[col1]*X_train[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\3337423945.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, wh

In [41]:
extended_X_train.head(1)

CRIM   ZN  INDUS  CHAS   NOX     RM   AGE     DIS  RAD    TAX  ...  \
105  0.13262  0.0   8.56   0.0  0.52  5.851  96.7  2.1069  5.0  384.0  ...   

     LSTATxCHAS  LSTATxNOX  LSTATxRM  LSTATxAGE  LSTATxDIS  LSTATxRAD  \
105         0.0     8.5644  96.36597   1592.649  34.700643      82.35   

     LSTATxTAX  LSTATxPTRATIO    LSTATxB  LSTATxLSTAT  
105    6324.48        344.223  6490.0035     271.2609  

[1 rows x 182 columns]

In [42]:
extended_X_train.shape

(354, 182)

In [43]:
extended_X_test = X_test.copy()

In [44]:
for col1 in X_test.columns:
    for col2 in X_test.columns:
        extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]

C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  extended_X_test[col1+'x'+col2] = X_test[col1]*X_test[col2]
C:\Users\smhrd\AppData\Local\Temp\ipykernel_8888\2007841065.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which ha

In [45]:
print(extended_X_train.shape)
print(extended_X_test.shape)

(354, 182)
(152, 182)


In [47]:
linear_model2 = LinearRegression()
linear_model2.fit(extended_X_train,y_train)

LinearRegression()

In [48]:
linear_result2=cross_val_score(linear_model2,extended_X_train,y_train,cv=5)
linear_result2

array([0.85037065, 0.73909773, 0.871558  , 0.81280662, 0.72009709])

In [49]:
linear_result2.mean()

0.7987860195213996

### Ridge vs Lasso
- Lasso : L1규제, 특정 계수들(w)이 0이 될 수 있음(자동 특성 선택)
- Ridge : L2규제, 골고루 규제 적용, 0에 가까워짐 (0이 되지 않음)

In [51]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [53]:
alpha_list = [0.001,0.01,0.1,1,10,100,1000]
ridge_coef_list = []  # 가중치 리스트 /계수값 담으르 리스트
lasso_coef_list = [] 

for a in alpha_list:
    r_model = Ridge(alpha=a)  #규제 강도에 따른 모델 생성
    l_model = Lasso(alpha=a)
    
    r_model.fit(X_train,y_train) #모델 학습 -> 계수들을 찾음
    l_model.fit(X_train,y_train)
    
    ridge_coef_list.append(r_model.coef_)
    lasso_coef_list.append(l_model.coef_)

In [54]:
ridge_coef_list

[array([-1.10642814e-01,  4.58831122e-02,  1.10225162e-01,  2.87497173e+00,
        -2.01044387e+01,  3.32562249e+00,  3.78998758e-03, -1.49564561e+00,
         3.12215452e-01, -1.44033290e-02, -9.89409141e-01,  9.80418169e-03,
        -5.71338884e-01]),
 array([-1.10583408e-01,  4.59040839e-02,  1.09600206e-01,  2.87153776e+00,
        -1.99462021e+01,  3.32727725e+00,  3.66120315e-03, -1.49323381e+00,
         3.11941685e-01, -1.44182502e-02, -9.87764498e-01,  9.81069556e-03,
        -5.71515261e-01]),
 array([-1.10038359e-01,  4.60981229e-02,  1.03855755e-01,  2.83921337e+00,
        -1.84907245e+01,  3.34226675e+00,  2.47917359e-03, -1.47105430e+00,
         3.09435875e-01, -1.45561429e-02, -9.72657904e-01,  9.87064113e-03,
        -5.73155817e-01]),
 array([-1.07191268e-01,  4.72032477e-02,  7.32716230e-02,  2.62499715e+00,
        -1.06865058e+01,  3.40934698e+00, -3.71408448e-03, -1.35237172e+00,
         2.96693285e-01, -1.53317924e-02, -8.92835538e-01,  1.01935384e-02,
       

In [57]:
X_train.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
105  0.13262   0.0   8.56   0.0  0.520  5.851  96.7  2.1069   5.0  384.0   
129  0.88125   0.0  21.89   0.0  0.624  5.637  94.7  1.9799   4.0  437.0   
399  9.91655   0.0  18.10   0.0  0.693  5.852  77.8  1.5004  24.0  666.0   
13   0.62976   0.0   8.14   0.0  0.538  5.949  61.8  4.7075   4.0  307.0   
292  0.03615  80.0   4.95   0.0  0.411  6.630  23.4  5.1167   4.0  245.0   

     PTRATIO       B  LSTAT  
105     20.9  394.05  16.47  
129     21.2  396.90  18.34  
399     20.2  338.16  29.97  
13      21.0  396.90   8.26  
292     19.2  396.90   4.70

In [63]:
ridge_df=pd.DataFrame(np.array(ridge_coef_list).T,
            columns=alpha_list)  # 전치

In [64]:
ridge_df

0.001      0.010      0.100      1.000     10.000    100.000   1000.000
0   -0.110643  -0.110583  -0.110038  -0.107191 -0.104976 -0.104396 -0.092228
1    0.045883   0.045904   0.046098   0.047203  0.049480  0.053652  0.051394
2    0.110225   0.109600   0.103856   0.073272  0.042027  0.043027  0.058634
3    2.874972   2.871538   2.839213   2.624997  1.843875  0.545354  0.088451
4  -20.104439 -19.946202 -18.490724 -10.686506 -2.038096 -0.214419 -0.012286
5    3.325622   3.327277   3.342267   3.409347  3.245610  1.852635  0.422435
6    0.003790   0.003661   0.002479  -0.003714 -0.008157  0.004937  0.033256
7   -1.495646  -1.493234  -1.471054  -1.352372 -1.222415 -1.109936 -0.524991
8    0.312215   0.311942   0.309436   0.296693  0.293107  0.330926  0.306604
9   -0.014403  -0.014418  -0.014556  -0.015332 -0.016737 -0.019065 -0.019462
10  -0.989409  -0.987764  -0.972658  -0.892836 -0.821742 -0.848960 -0.592045
11   0.009804   0.009811   0.009871   0.010194  0.010545  0.010196  0.009198
12  -0.571339  -0.571515  -0.573156  -0.582994 -0.611770 -0.711510 -0.771737

In [65]:
lasso_df=pd.DataFrame(np.array(lasso_coef_list).T,
            columns=alpha_list)  # 전치

In [66]:
lasso_df

0.001      0.010     0.100     1.000     10.000    100.000   1000.000
0   -0.110524  -0.109396 -0.102829 -0.077139 -0.000000 -0.000000      -0.0
1    0.045921   0.046287  0.048579  0.046325  0.013448  0.000000       0.0
2    0.109033   0.097675  0.032181  0.000000 -0.000000 -0.000000      -0.0
3    2.855985   2.681645  1.113953  0.000000  0.000000  0.000000       0.0
4  -19.799695 -16.897675 -0.000000 -0.000000  0.000000 -0.000000      -0.0
5    3.326848   3.339553  3.315938  0.665193  0.000000  0.000000       0.0
6    0.003581   0.001571 -0.007614  0.021227  0.000000 -0.000000      -0.0
7   -1.490750  -1.444258 -1.160030 -0.824769 -0.000000  0.000000       0.0
8    0.311734   0.307137  0.283668  0.259428  0.000000 -0.000000      -0.0
9   -0.014435  -0.014736 -0.016694 -0.015940 -0.009064 -0.019695      -0.0
10  -0.986344  -0.957104 -0.792642 -0.740131 -0.000000 -0.000000      -0.0
11   0.009817   0.009943  0.010704  0.009388  0.008796  0.005538       0.0
12  -0.571840  -0.576527 -0.612554 -0.779151 -0.581963 -0.000000      -0.0

### 다른 회귀 모형

##### 결정 트리 회귀 모형

In [69]:
from sklearn.tree import DecisionTreeRegressor

In [70]:
tree_reg = DecisionTreeRegressor(max_depth=5)
tree_reg.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=5)

In [71]:
from sklearn.model_selection import GridSearchCV

In [73]:
# GridSearch 사용가능
# 알아보고 싶은 조합의 주요 매개변수 정의
params = {'max_depth':[3,5,7],
         'max_leaf_nodes':[4,6,8],
         'min_samples_split':[4,6,8],
         'min_samples_leaf':[3,5,7]}

grid = GridSearchCV(tree_reg,params, cv=5)
# grid.fit(X_train,y_train)

##### 랜덤 포레스트 회귀 모형

In [74]:
from sklearn.ensemble import RandomForestRegressor

In [75]:
rf_reg = RandomForestRegressor(max_depth=5,n_estimators=1000)

##### XGBoost 회귀모형

In [76]:
from xgboost import XGBRFRegressor